### PR TITLE
Fixes (maybe) escaping issue #1

### PR DESCRIPTION
**Pull request by kuraga**
@scottkmaxwell , @codecobblers , merge, please!

### CODE REVIEW

**Comment by scottkmaxwell** [comment]
So this fixes the problem you reported? If so, I'll trust that it works and just accept your pull request.

**Comment by kuraga** [comment]
@scottkmaxwell , I'm very glad for your reply!
Yes, it works for year in my project.
I could promise to write tests but I would be very glad to see a new version of this package in PyPI with that patch.
Ok? Thanks.

**Comment by scottkmaxwell** [comment]
It's up. A bunch of my tests were failing (not your fault) so I fixed all of those too. Let me know if you run into any trouble.

**Comment by kuraga** [comment]
Thanks VERY much!

**Pull request merged**
